### ISSUE TITLE
One concern about paper detail

### ISSUE THREAD

**Issue by CannotBeFatAnyMore** [ZhenZHAO/AD-MT#2]
Dear Zhen Zhao,
Thanks again for your briliant thought about ensemble idea for dual temporal teacher architeture, it's a delicate and fancy idea.There's one point that I still concern is description in abstract:"The RPA schedules the alternating diverse updating process *with complementary data batches*, distinct data augmentation, and random switching periods to encourage diverse reasoning from different teaching perectives." I will be grateful if you can show your opinion about this statement! Thanks!

**Comment by CannotBeFatAnyMore** [comment]
To be specifically, I don’t know complementary data batches refer to what

**Comment by ZhenZHAO** [comment]
I thought the statement can be clear. RPA is used to obtain two different teacher, but how? use these metioned techniques,
- "complementary data batches", considering within a training epoch, two models are updated upon different data batches.
- 'distinct data augmentation',  color-based for one, cutmix-based for another.
- "random switching periods", the alternation period, the key is to be random.
